name: Generate Contributions Snake

# Chuyển GITHUB_TOKEN thành write để có thể commit
permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install @platane/snk
        run: npm install -g @platane/snk

      - name: Generate snake.svg
        run: snk --username SmallChicken2k5 --output snake.svg

      - name: Commit & Push updated snake.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add snake.svg
          if git diff --cached --exit-code; then
            echo "✅ No changes"
          else
            git commit -m "chore: update contributions snake"
            git push
          fi
