name: Generate Contributions Snake

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Hàng ngày lúc 00:00 UTC

jobs:
  generate-snake:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code (thêm token để push được)
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      # 2. Generate Snake SVG using platane/snk Action
      - uses: platane/snk@v3
        with:
          github_user_name: SmallChicken2k5
          outputs: |
            snake.svg

      # 3. Commit & push nếu có thay đổi
      - name: Commit & Push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add snake.svg
          if git diff --cached --exit-code; then
            echo "✅ No changes to snake.svg"
          else
            git commit -m "chore: update contributions snake"
            git push
          fi
